# Generated by Django 4.2 on 2025-08-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cinturon', models.CharField(choices=[('Blanco', 'Blanco'), ('Amarillo', 'Amarillo'), ('Naranja', 'Naranja'), ('Verde', 'Verde'), ('Azul', 'Azul'), ('Marrón', 'Marrón'), ('Negro', 'Negro')], default='Blanco', max_length=20)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Retirado', 'Retirado')], default='Activo', max_length=20)),
            ],
            options={
                'db_table': 'alumnos',
            },
        ),
    ]
